python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb01.txt --id chb01 &>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb02.txt --id chb02 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb03.txt --id chb03 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb04.txt --id chb04 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb05.txt --id chb05 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb06.txt --id chb06 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb07.txt --id chb07 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb08.txt --id chb08 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb09.txt --id chb09 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb10.txt --id chb10 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb11.txt --id chb11 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb12.txt --id chb12 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb13.txt --id chb13 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb14.txt --id chb14 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb15.txt --id chb15 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb16.txt --id chb16 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb17.txt --id chb17 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb18.txt --id chb18 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb19.txt --id chb19 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb20.txt --id chb20 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb21.txt --id chb21 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb22.txt --id chb22 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb23.txt --id chb23 &>>indexes.out
python python/utils/generate_detection_indexes.py --index ../etc/indexes/index_chb24.txt --id chb24 &>>indexes.out
